#!/usr/bin/env sh

BIN_DIR=./bin/

env GOOS=linux GOARCH=amd64 go build . &&
env GOOS=windows GOARCH=amd64 go build .

if [ $? -eq 0 ] 
then
    mv cscan cscan.exe $BIN_DIR
else
    echo "Error in build!"
fi
